### ISSUE TITLE
`throwOnError` doesn't work in dev mode

### ISSUE THREAD

**Issue by asakusuma** [tildeio/broccoli-typescript-compiler#61]
If there's a TypeScript error, and `throwOnError` is set to `true`, and you run a dev build, you'll see the errors in the console, but the build will succeed. If you run the prod build, it throws as expected.

Seen on version `2.1.0`

cc @krisselden

**Comment by tomdale** [comment]
I wrote a suite of tests in #62 to verify the reported behavior, but could not reproduce it. Examining the source code, I don't see any obvious ways the reported behavior could manifest, and none of the changes since 2.1.0 have touched this functionality.

@asakusuma Can you provide steps to reproduce? Are you sure that you're setting `throwOnError` in the "root" plugin options and not inside `tsconfig` or `compilerOptions`?

**Comment by stefanpenner** [comment]
I think this can be closed, there was a rather complicated TS build and the options set did not cover all variations of TS usage.

I'll gladly reopen if i misunderstood. Thanks @tomdale for writing the failing test.
